export const contracts = [
    {
      contract: "IT Services Agreement with TechCorp Ltd.",
      owner: "Bob Smith",
      value: "$285,000",
      vendor: "TechCorp Ltd.",
      review: "Performance Review",
      renewalStart: "2025-01-01",
      renewalEnd: "2025-02-08",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-05",
          eventEndDate: "2025-01-10",
          handledBy: "Alice Johnson",
          note: "Initial meeting to discuss contract renewal terms and performance metrics.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-11",
          eventEndDate: "2025-01-16",
          handledBy: "John Carter",
          note: "Reviewed vendor's performance reports and compliance with SLA terms.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-19",
          eventEndDate: "2025-01-31",
          handledBy: "Samantha Lee",
          note: "Conducted negotiation sessions to finalize updated pricing and service adjustments.",
        },
      ],
    },
    {
      contract: "Office Lease Contract with Realty Ventures",
      owner: "Carol White",
      value: "$552,000",
      vendor: "Realty Ventures",
      review: "Cost Optimization",
      renewalStart: "2025-01-16",
      renewalEnd: "2025-02-10",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-10",
          eventEndDate: "2025-01-15",
          handledBy: "Sarah Johnson",
          note: "Initial review of contract terms completed.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-16",
          eventEndDate: "2025-01-21",
          handledBy: "Mark Lee",
          note: "Cost optimization strategies discussed.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-21",
          eventEndDate: "2025-02-02",
          handledBy: "Carol White",
          note: "Final terms negotiated with the vendor.",
        },
      ],
    },
    {
      contract: "SaaS Subscription with CloudEase Inc.",
      owner: "Carol White",
      value: "$85,000",
      vendor: "CloudEase Inc.",
      review: "Feature Review",
      renewalStart: "2025-01-19",
      renewalEnd: "2025-02-16",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-14",
          eventEndDate: "2025-01-18",
          handledBy: "David Miller",
          note: "Service performance evaluated.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-19",
          eventEndDate: "2025-01-27",
          handledBy: "Anna Taylor",
          note: "Feature requirements reviewed.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-27",
          eventEndDate: "2025-02-08",
          handledBy: "Carol White",
          note: "Vendor agreement on feature updates finalized.",
        },
      ],
    },
    {
      contract: "Maintenance Agreement with EquipCare Ltd.",
      owner: "Dan Brown",
      value: "$120,000",
      vendor: "EquipCare Ltd.",
      review: "Equipment Analysis",
      renewalStart: "2025-01-21",
      renewalEnd: "2025-02-04",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-15",
          eventEndDate: "2025-01-20",
          handledBy: "Michael Green",
          note: "Initial inspection of maintenance logs.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-21",
          eventEndDate: "2025-01-26",
          handledBy: "Laura Wilson",
          note: "Equipment utilization report prepared.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-29",
          eventEndDate: "2025-02-05",
          handledBy: "Dan Brown",
          note: "Revised maintenance schedule agreed upon.",
        },
      ],
    },
    {
      contract: "Vendor Supply Contract with MegaSupply Co.",
      owner: "Eve Davis",
      value: "$432,000",
      vendor: "MegaSupply Co.",
      review: "Vendor Performance",
      renewalStart: "2025-01-23",
      renewalEnd: "2025-02-27",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-18",
          eventEndDate: "2025-01-22",
          handledBy: "Emma Davis",
          note: "Supply chain evaluation completed.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-23",
          eventEndDate: "2025-01-31",
          handledBy: "Chris Brown",
          note: "Vendor KPIs analyzed.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-02-03",
          eventEndDate: "2025-02-19",
          handledBy: "Eve Davis",
          note: "Long-term supply agreement renegotiated.",
        },
      ],
    },
    {
      contract: "Software Maintenance Contract with DataSoft Solutions",
      owner: "Alice Cooper",
      value: "$300,000",
      vendor: "DataSoft Solutions",
      review: "Security Enhancements",
      renewalStart: "2025-02-01",
      renewalEnd: "2025-02-20",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-26",
          eventEndDate: "2025-01-30",
          handledBy: "Sophia Martinez",
          note: "Initial assessment of software vulnerabilities.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-02-01",
          eventEndDate: "2025-02-10",
          handledBy: "Liam Harris",
          note: "Detailed security enhancement plan created.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-02-11",
          eventEndDate: "2025-02-18",
          handledBy: "Alice Cooper",
          note: "Final approval on security measures and cost.",
        },
      ],
    },
    {
      contract: "Outsourcing Contract with ProStaff Services",
      owner: "John Doe",
      value: "$150,000",
      vendor: "ProStaff Services",
      review: "Resource Optimization",
      renewalStart: "2025-02-05",
      renewalEnd: "2025-02-25",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-02-01",
          eventEndDate: "2025-02-04",
          handledBy: "Ethan Moore",
          note: "Preliminary evaluation of outsourcing performance.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-02-05",
          eventEndDate: "2025-02-15",
          handledBy: "Mia Anderson",
          note: "Optimization strategies reviewed.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-02-16",
          eventEndDate: "2025-02-24",
          handledBy: "John Doe",
          note: "Agreed on resource allocation changes.",
        },
      ],
    },
    {
      contract: "IT Services Agreement with TechCorp Ltd.",
      owner: "Bob Smith",
      value: "$285,000",
      vendor: "TechCorp Ltd.",
      review: "Performance Review",
      renewalStart: "2025-01-01",
      renewalEnd: "2025-02-08",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-05",
          eventEndDate: "2025-01-10",
          handledBy: "Alice Johnson",
          note: "Initial meeting to discuss contract renewal terms and performance metrics.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-11",
          eventEndDate: "2025-01-16",
          handledBy: "John Carter",
          note: "Reviewed vendor's performance reports and compliance with SLA terms.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-19",
          eventEndDate: "2025-01-31",
          handledBy: "Samantha Lee",
          note: "Conducted negotiation sessions to finalize updated pricing and service adjustments.",
        },
      ],
    },
    {
      contract: "Office Lease Contract with Realty Ventures",
      owner: "Carol White",
      value: "$552,000",
      vendor: "Realty Ventures",
      review: "Cost Optimization",
      renewalStart: "2025-01-16",
      renewalEnd: "2025-02-10",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-10",
          eventEndDate: "2025-01-15",
          handledBy: "Sarah Johnson",
          note: "Initial review of contract terms completed.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-16",
          eventEndDate: "2025-01-21",
          handledBy: "Mark Lee",
          note: "Cost optimization strategies discussed.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-21",
          eventEndDate: "2025-02-02",
          handledBy: "Carol White",
          note: "Final terms negotiated with the vendor.",
        },
      ],
    },
    {
      contract: "SaaS Subscription with CloudEase Inc.",
      owner: "Carol White",
      value: "$85,000",
      vendor: "CloudEase Inc.",
      review: "Feature Review",
      renewalStart: "2025-01-19",
      renewalEnd: "2025-02-16",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-14",
          eventEndDate: "2025-01-18",
          handledBy: "David Miller",
          note: "Service performance evaluated.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-19",
          eventEndDate: "2025-01-27",
          handledBy: "Anna Taylor",
          note: "Feature requirements reviewed.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-27",
          eventEndDate: "2025-02-08",
          handledBy: "Carol White",
          note: "Vendor agreement on feature updates finalized.",
        },
      ],
    },
    {
      contract: "Maintenance Agreement with EquipCare Ltd.",
      owner: "Dan Brown",
      value: "$120,000",
      vendor: "EquipCare Ltd.",
      review: "Equipment Analysis",
      renewalStart: "2025-01-21",
      renewalEnd: "2025-02-04",
      stages: [
        {
          eventName: "Check-In",
          eventStartDate: "2025-01-15",
          eventEndDate: "2025-01-20",
          handledBy: "Michael Green",
          note: "Initial inspection of maintenance logs.",
        },
        {
          eventName: "Analysis",
          eventStartDate: "2025-01-21",
          eventEndDate: "2025-01-26",
          handledBy: "Laura Wilson",
          note: "Equipment utilization report prepared.",
        },
        {
          eventName: "Negotiation",
          eventStartDate: "2025-01-29",
          eventEndDate: "2025-02-05",
          handledBy: "Dan Brown",
          note: "Revised maintenance schedule agreed upon.",
        },
      ],
    },
  ];